version: "3"

networks:
  pmd-services-net:

services:
  keycloak:
    image: jboss/keycloak
    restart: "no"
    environment:
        KEYCLOAK_USER: "admin"
        KEYCLOAK_PASSWORD: "admin"
    ports:
      - "7080:8080"
    volumes:
      - ./deployments/:/opt/jboss/keycloak/standalone/deployments/
    networks:
      - pmd-services-net
